name: Deploy to production
on:
  push:
    branches:
      - main
jobs:
  Testing:
    env:
      DATABASE_URL: ${{secrets.DATABASE_URL}}
      REDIS_HOST: ${{secrets.REDIS_HOST}}
      REDIS_PASS: ${{secrets.REDIS_PASS}}
      REDIS_PORT: ${{secrets.REDIS_PORT}}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'npm'
    - run: npm install
    - run: npm test
  Deploy:
    env:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      DATABASE_URL: ${{secrets.DATABASE_URL}}
      REDIS_HOST: ${{secrets.REDIS_HOST}}
      REDIS_PASS: ${{secrets.REDIS_PASS}}
      REDIS_PORT: ${{secrets.REDIS_PORT}}
    needs: Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - run: npm ci
      - run: npm install -g serverless
      - run: npm run db:deploy
      - run: serverless deploy -s prod