name: Pull Request Flow

on:
    pull_request:
        branches:
            - master
            - develop

jobs:
    Testing:
      env:
        DATABASE_URL: ${{secrets.DEV_DATABASE_URL}}
        REDIS_HOST: ${{secrets.DEV_REDIS_HOST}}
        REDIS_PASS: ${{secrets.DEV_REDIS_PASS}}
        REDIS_PORT: ${{secrets.DEV_REDIS_PORT}}
        REDIS_ACTIVE: ${{secrets.DEV_REDIS_ACTIVE}}
        JWT_KEY: ${{secrets.DEV_JWT_KEY}}
        JWT_EXPIRES: ${{secrets.DEV_JWT_EXPIRES}}
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - run: npm install
      - run: npm test